config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  # get '/users/:id/', to: 'users#show', as: 'user'
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users
  resources :blogs
  resources :comments
  # root to: "blogs#landing"

  devise_scope :user do
    authenticated :user do
      # root :to => "users#show", :id => current_user.id
      # root to: "users#show"
      root to: "users#findpage"
    end

    unauthenticated do
      root :to => "users#landing"
    end
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :blog
end

app/models/user.rb
class User < ApplicationRecord
  has_many :blogs, dependent: :destroy
  has_many :comments, dependent: :destroy
  validates_uniqueness_of :username # make usernames unique
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  # include DeviseWhitelist

  before_action :configure_permitted_parameters, if: :devise_controller?



  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  
  # listing all blogs
  def index
    @all_blogs = Blog.all
  end

  # creating a new blog needs object for form
  def new
    # @new_blog = Blog.new
  end

  # creating a new blog action
  def create
    
    new_blog = current_user.blogs.build(blog_params)

    if (blog_params[:content] != "")
      if new_blog.save
        
        redirect_back(fallback_location: root_path)
        flash[:notice] = "New blog published!"

      else
        redirect_back(fallback_location: root_path)
        flash[:alert] = "Error: Failed to publish, try again!"
      end
    else
      flash[:alert] = "Error: Content can't be blank!"
      redirect_back(fallback_location: root_path)
    end

  end

  def update
    updated_blog = Blog.find_by_id(params[:id])

    if (blog_params[:content] != "")
      if updated_blog.update(blog_params)
        flash[:notice] = 'Your blog was updated successfully!'
        redirect_back(fallback_location: root_path)
      else
        flash[:alert] = 'Error: Blog not updated, try again!'
        redirect_back(fallback_location: root_path)
      end
    else
      flash[:alert] = "Error: Content can't be blank!"
      redirect_back(fallback_location: root_path)
    end

  end
  
  def show
    @page_blog_id = params[:id]  # this is for current blog
    # current_user for current logged in user

    @page_blog = Blog.find_by_id(@page_blog_id)

    
  end

  def destroy
    blog = Blog.find_by_id(params[:id])
    blog.destroy
    flash[:notice] = 'Your blog was removed!'
    # redirect_to root_path
    redirect_back(fallback_location: root_path)
    
  end



private

  def blog_params
    params.require(:blog).permit(:content, :user_id)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    # @new_comment = Comment.new
  end

  
  def create
    
    new_comment = current_user.comments.build(comment_params)    

    if (comment_params[:content] != "")
      if new_comment.save
        redirect_back(fallback_location: root_path)
        flash[:notice] = "New comment published!"
      else
        redirect_back(fallback_location: root_path)
        flash[:alert] = "Error: Failed to publish, try again!"
      end
    else
      flash[:alert] = "Error: Content can't be blank!"
      redirect_back(fallback_location: root_path)
    end

  end

  def destroy
    @target_comment = Comment.find_by_id(params[:id])
    @target_comment.destroy
    flash[:notice] = 'Your comment was removed!'
    # redirect_to root_path
    redirect_back(fallback_location: root_path)
  end

  def update
    updated_comment = Comment.find_by_id(params[:id])

    if (comment_params[:content] != "")

      if updated_comment.update(comment_params)
        flash[:notice] = 'Your comment was updated successfully!'
        redirect_back(fallback_location: root_path)
      else
        flash[:alert] = 'Error: Comment not updated, try again!'
        redirect_back(fallback_location: root_path)
      end

    else
      flash[:alert] = "Error: Content can't be blank!"
      redirect_back(fallback_location: root_path)
    end
  end

private

  def comment_params
    params.require(:comment).permit(:content, :user_id, :blog_id)
  end

end

app/controllers/concerns/devise_whitelist.rb
# module DeviseWhitelist 
#   extend ActiveSupport::Concern 
  
#    included do 
#     before_filter :configure_permitted_parameters, if: :devise_controller? 
#   end 
  
#   def configure_permitted_parameters 
#    devise.parameter.sanitzier.permit(:sign_up, keys: [:email, :username, :password]) 
#    devise.parameter.sanitzier.permit(:account_update, keys: [:email, :username, :password]) 
#   end  
  
#   end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
  end
  
  def show
    @page_user_id = (params[:id] || current_user.id).to_i
    
    @page_user = User.find_by_id(@page_user_id)

    # @page_user = User.find_by_id(@page_user_id)


    # if user for this page doesn't exist
    if !@page_user
      render '/users/notfound.html'
      # render '/users/notfound.html'
      # redirect_to 'users/' + current_user.id.to_s
    end

    
  end


  def findpage
    # this makes sure url has full path
    redirect_to user_path(current_user.id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end
 
  def resource
    @resource ||= User.new
  end
 
  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/index.html.erb
<div class="main__profile">

    <div class="main__profile__welcome">
      Bad recent blogs
    </div>
  
  
    <% Blog.all.reverse.each do |ea_blog| %>
      <div class="main__profile__history">
        <div class="main__profile__history__relative">
          <div class="main__profile__history__timestamp"> 
            <%= ea_blog.updated_at.to_formatted_s(:long) %>
          </div>
          <a href="/users/<%= ea_blog.user.id %>" class="main__profile__history__writers">
            <%= ea_blog.user.username %>
          </a>
          
        </div>
        <%= form_for ea_blog, url: blog_path(ea_blog), html: {class: "main__profile__history__form"} do |f| %>
          <%= f.text_area(:content, rows: 3, placeholder: 'editing blog', class: 'textarea_placeholder main__profile__history__content general__textarea__scrollbar', maxlength: 149, 'data-blogid'=>ea_blog.id ) %>
          <div class="main__profile__history__buttons">
            <% if (user_signed_in?) %>
  
              <div class="main__profile__history__buttons__start" data-blogid="<%=ea_blog.id%>">
                <% if (ea_blog.user_id == current_user.id) %>
                  <div class="main__profile__history__content__start_edit">
                    edit
                  </div>
                  <div class="main__profile__history__content_start_delete">
                    delete
                  </div>
                <% end %>
  
                <div class="main__profile__history__content_start_reply" data-blogid="<%=ea_blog.id%>">
                  reply
                </div>
              </div>
            <% end %>
  
            <div class="main__profile__history__content_editchoice" data-blogid="<%=ea_blog.id%>">
              <%= f.submit "update blog", class: 'main__profile__history__buttons__save_confirm' %>
  
              <div class="main__profile__history__content_edit_cancel">
                cancel
              </div>
            </div>
  
            <div class="main__profile__history__content_deletechoice" data-blogid="<%=ea_blog.id%>">
              <%= link_to 'confirm delete', '/blogs/' + ea_blog.id.to_s, method: :delete, class: "main__profile__history__buttons__delete_confirm" %>
              <div class="main__profile__history__content_delete_cancel">
                cancel
              </div>
            </div>
          </div>
        
        
        <% end %>
  
        <ul>
          <!-- new comment form at end of comments -->
          <div class="main__profile__history__comments">
            <% if user_signed_in? %>
              <li class="main__profile__history__comments_new_li" data-blogid="<%=ea_blog.id%>">
                <%= form_for Comment.new, html: {class: "main__profile__history__comments__form"} do |f| %>
                  <%= f.hidden_field :user_id, value: current_user.id %>
                  <%= f.hidden_field :blog_id, value: ea_blog.id %>
                  <%= f.text_area(:content, rows: 2, placeholder: 'new comment', class: "textarea_placeholder main__profile__history__comments__txtnew general__textarea__scrollbar", maxlength: 149) %>
                  <%= f.submit "publish comment", class: 'main__profile__history_comments__form_submit'%>
                <% end %>
              </li>
            <% end %>
  
            <% ea_blog.comments.all.reverse.each do |ea_comment| %>
              <li class="main__profile__history__comments_li">
                <div class="main__profile__history__comments_li_head">
                  <div class="main__profile__history__comments__timestamp">
                    <%= ea_comment.updated_at.to_formatted_s(:long) %>
                  </div>
                  
                  <a href="/users/<%= ea_comment.user_id %>" class="main__profile__history__comments__writers">
                    <%= ea_comment.user.username %>
                  </a>
                </div>
                <%= form_for ea_comment, url: comment_path(ea_comment), html: {class: "main__profile__history__comments__form"} do |f| %>
                  <%= f.text_area(:content, rows: 1, placeholder: 'editing comment', class: 'textarea_placeholder main__profile__history__comments__content general__textarea__scrollbar', maxlength: 149, 'data-commentid'=>ea_comment.id ) %>
  
                  <div class="main__profile__history__comments__buttons">
                    <% if (user_signed_in?) %>
          
                      <!-- toggles on/off -->
                      <div class="main__profile__history__comments__start" data-commentid="<%= ea_comment.id %>">
                        <% if (ea_comment.user_id == current_user.id) %>
                          <div class="main__profile__history__comments__start_edit">
                            edit
                          </div>
                          <div class="main__profile__history__comments_start_delete">
                            delete
                          </div>
                        <% end %>
          
                        <div class="main__profile__history__content_start_reply" data-blogid="<%=ea_blog.id%>">
                          reply
                        </div>
                      </div>
                    <% end %>
          
                    <!-- toggles on/off -->
                    <div class="main__profile__history__comments_editchoice" data-commentid="<%=ea_comment.id%>">
                      <%= f.submit "update blog", class: 'main__profile__history__comments__buttons__save_confirm' %>
          
                      <div class="main__profile__history__comments_edit_cancel">
                        cancel
                      </div>
                    </div>
          
                    <!-- toggles on/off -->
                    <div class="main__profile__history__comments_deletechoice" data-commentid="<%=ea_comment.id%>">
                      <%= link_to 'confirm delete', '/comments/' + ea_comment.id.to_s, method: :delete, class: "main__profile__history__comments__buttons__delete_confirm" %>
                      <div class="main__profile__history__comments_delete_cancel">
                        cancel
                      </div>
                    </div>
                  </div>
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
                  <%# f.submit "edit comment", class: 'main__profile__history__comments__content__btnsubmit'%>
                  <%# link_to 'Destroy', '/comments/' + ea_comment.id.to_s, method: :delete %>
                <% end %>
  
              </li>
            <% end %>
            
          </div>
          
        </ul>
  
      </div>
  
  
  
    <% end %>
  
  </div>
  
  <!-- div for javascript to find -->
  
  <div class="main__profile_loaded"></div>

app/views/blogs/new.html.erb
<h1>new blog</h1>

<%= form_for @new_blog do |f| %>

  
  <%= f.text_field :content %>
  <%= f.submit %>

<% end %>

app/views/blogs/show.html.erb
<h1> Blog show </h1>


<%= @page_blog.user.username %> / 
<%= @page_blog.created_at.to_formatted_s(:long) %><br>
<%= @page_blog.content %>

<ul>
    
  <% @page_blog.comments.all.reverse.each do |ea_comment| %>
  <li>
    <%= ea_comment.user.username %> / 
    <%= ea_comment.created_at.to_formatted_s(:long) %><br>
    <%= ea_comment.content %><br>
    <br>
  </li>
  <% end %>
  
  <li>
    <% if @page_blog %>
      <%= form_for @page_blog.comment.new do |f| %>
        <%= f.text_field :content %>
        <%= f.submit %>
      <% end %>
    <% end %>
  </li>

  
    
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bad Blogs</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="nav">
      <!-- general links on left side -->
      <div class="nav__left">
        <% if params[:action] != 'landing' %>
          <%= link_to 'BadBlogs.io', root_path, :class => "nav__left__option bold button_down" %>
        <% end %>
        <%= link_to 'Blogs', blogs_path, :class => "nav__left__option button_down" %>
        <%= link_to 'People', users_path, :class => "nav__left__option button_down" %>
      </div>

      <!-- account based options on right side -->
      <div class="nav__account">
        <% if !user_signed_in? %>
          <!-- if not logged in -->

          <% if !(params[:controller] == "devise/registrations" && (params[:action] == 'create' || params[:action] == 'new')) %>
            
            <%= form_for(resource, as: resource_name, url: session_path(resource_name), class: "nav__account__option") do |f| %>
              <%= f.email_field :email, autofocus: true, autocomplete: "email", :class => "nav__account__form__field", placeholder: "email" %>
              <%= f.password_field :password, autocomplete: "off", :class => "nav__account__form__field", placeholder: "pass" %>
              <%= f.submit " > ", :class => "nav__account__option_signin button_down" %>            
            <% end %>
            
          <% end %>

        <% else %>
          <!-- if logged in -->

          <%= link_to current_user.username, user_path(current_user.id), :class => "nav__account__option button_down bold" %>
          <%= link_to edit_user_registration_path, :class => "nav__account__option button_down nav__account__option_edit_wrapper" do %>
            <div class="nav__all__option_edit_image">edit</div>
          <% end %>
          <%= link_to 'logout', destroy_user_session_path, method: :delete, :class => "nav__account__option button_down" %>

        <% end %>
      </div>
    </div>

    <!-- key can be "notice" or "alert" -->
    <% flash.each do |key, value| %>
      <div class="<%= key %>">
        <%= value %>
      </div>
    <% end %>

    <!-- render offset for navbar -->
    <div class="spacer"></div>

    <!-- where everything renders -->
    <div class="main">
      
      <%= yield %>

    </div>
    
    
  </body>
</html>

app/views/users/index.html.erb
<div class="main__people">
  <div class="main__people__title">
    Browse other users
  </div>
  <div class="spacer">
  </div>
  
  <% User.all.reverse.each do |ea_user| %>
    <a class="main__people__user" href="/users/<%= ea_user.id %>">
      <% if ea_user.username %>
        <%= ea_user.username %>
      <% else %>
        <%= ea_user.email %>
      <% end %>
    </a>
  <% end %>
</div>

app/views/users/landing.html.erb
<div class="main__landing">

  <div class="main__landing__spacer1"></div>

  <div class="main__landing__title">
    BadBlogs<span class="main__landing__title_highlight">.io</span>
  </div>

  <div class="main__landing__spacer1"></div>

  <%= link_to 'Sign Up', new_user_registration_path, :class => "main__landing__signup button_down" %>




</div>

app/views/users/notfound.html.erb
<div class="main__profile">
  <div class="main__profile__welcome">
    This user doesn't exist
  </div>
</div>

app/views/users/show.html.erb
<div class="main__profile">

  <div class="main__profile__welcome">
    Bad <span class="main__landing__title_highlight"><%= @page_user.username %></span> blogs
  </div>
  
  <% if user_signed_in? %>
    <!-- have to be signed in to post new blog -->
    <%# current_user.id %>
    <%# @page_user_id %>

    

    <% if current_user.id == @page_user_id %>
      <!-- have to be logged in on your user page to post new blog -->

      <div class="main__profile__new">
        <%= form_for Blog.new do |f| %>
          <%= f.hidden_field :user_id, value: current_user.id %>
          <%# f.text_field :content %>
          <%= f.text_area(:content, rows: 3, placeholder: 'new blog', class: "textarea_placeholder main__profile__new__text general__textarea__scrollbar", maxlength: 149) %>
          <%= f.submit "Publish", class: 'main__profile__new__submit' %>
        <% end %>
      </div>
    <% else %>
      <!-- if not a match, it's someone elses page -->

    <% end %>
  <% end %>


  <% @page_user.blogs.all.reverse.each do |ea_blog| %>
    <div class="main__profile__history">
      <div class="main__profile__history__relative">
        <div class="main__profile__history__timestamp"> 
          <%= ea_blog.updated_at.to_formatted_s(:long) %>
        </div>
        <a href="/users/<%= ea_blog.user.id %>" class="main__profile__history__writers">
          <%= ea_blog.user.username %>
        </a>
        
      </div>
      <%= form_for ea_blog, url: blog_path(ea_blog), html: {class: "main__profile__history__form"} do |f| %>
        <%= f.text_area(:content, rows: 3, placeholder: 'editing blog', class: 'textarea_placeholder main__profile__history__content general__textarea__scrollbar', maxlength: 149, 'data-blogid'=>ea_blog.id ) %>
        <div class="main__profile__history__buttons">
          <% if (user_signed_in?) %>

            <div class="main__profile__history__buttons__start" data-blogid="<%=ea_blog.id%>">
              <% if (ea_blog.user_id == current_user.id) %>
                <div class="main__profile__history__content__start_edit">
                  edit
                </div>
                <div class="main__profile__history__content_start_delete">
                  delete
                </div>
              <% end %>

              <div class="main__profile__history__content_start_reply" data-blogid="<%=ea_blog.id%>">
                reply
              </div>
            </div>
          <% end %>

          <div class="main__profile__history__content_editchoice" data-blogid="<%=ea_blog.id%>">
            <%= f.submit "update blog", class: 'main__profile__history__buttons__save_confirm' %>

            <div class="main__profile__history__content_edit_cancel">
              cancel
            </div>
          </div>

          <div class="main__profile__history__content_deletechoice" data-blogid="<%=ea_blog.id%>">
            <%= link_to 'confirm delete', '/blogs/' + ea_blog.id.to_s, method: :delete, class: "main__profile__history__buttons__delete_confirm" %>
            <div class="main__profile__history__content_delete_cancel">
              cancel
            </div>
          </div>
        </div>
      
      
      <% end %>

      <ul>
        <!-- new comment form at end of comments -->
        <div class="main__profile__history__comments">
          <% if user_signed_in? %>
            <li class="main__profile__history__comments_new_li" data-blogid="<%=ea_blog.id%>">
              <%= form_for Comment.new, html: {class: "main__profile__history__comments__form"} do |f| %>
                <%= f.hidden_field :user_id, value: current_user.id %>
                <%= f.hidden_field :blog_id, value: ea_blog.id %>
                <%= f.text_area(:content, rows: 2, placeholder: 'new comment', class: "textarea_placeholder main__profile__history__comments__txtnew general__textarea__scrollbar", maxlength: 149) %>
                <%= f.submit "publish comment", class: 'main__profile__history_comments__form_submit'%>
              <% end %>
            </li>
          <% end %>

          <% ea_blog.comments.all.reverse.each do |ea_comment| %>
            <li class="main__profile__history__comments_li">
              <div class="main__profile__history__comments_li_head">
                <div class="main__profile__history__comments__timestamp">
                  <%= ea_comment.updated_at.to_formatted_s(:long) %>
                </div>
                
                <a href="/users/<%= ea_comment.user_id %>" class="main__profile__history__comments__writers">
                  <%= ea_comment.user.username %>
                </a>
              </div>
              <%= form_for ea_comment, url: comment_path(ea_comment), html: {class: "main__profile__history__comments__form"} do |f| %>
                <%= f.text_area(:content, rows: 1, placeholder: 'editing comment', class: 'textarea_placeholder main__profile__history__comments__content general__textarea__scrollbar', maxlength: 149, 'data-commentid'=>ea_comment.id ) %>

                <div class="main__profile__history__comments__buttons">
                  <% if (user_signed_in?) %>
        
                    <!-- toggles on/off -->
                    <div class="main__profile__history__comments__start" data-commentid="<%= ea_comment.id %>">
                      <% if (ea_comment.user_id == current_user.id) %>
                        <div class="main__profile__history__comments__start_edit">
                          edit
                        </div>
                        <div class="main__profile__history__comments_start_delete">
                          delete
                        </div>
                      <% end %>
        
                      <div class="main__profile__history__content_start_reply" data-blogid="<%=ea_blog.id%>">
                        reply
                      </div>
                    </div>
                  <% end %>
        
                  <!-- toggles on/off -->
                  <div class="main__profile__history__comments_editchoice" data-commentid="<%=ea_comment.id%>">
                    <%= f.submit "update blog", class: 'main__profile__history__comments__buttons__save_confirm' %>
        
                    <div class="main__profile__history__comments_edit_cancel">
                      cancel
                    </div>
                  </div>
        
                  <!-- toggles on/off -->
                  <div class="main__profile__history__comments_deletechoice" data-commentid="<%=ea_comment.id%>">
                    <%= link_to 'confirm delete', '/comments/' + ea_comment.id.to_s, method: :delete, class: "main__profile__history__comments__buttons__delete_confirm" %>
                    <div class="main__profile__history__comments_delete_cancel">
                      cancel
                    </div>
                  </div>
                </div>



















                <%# f.submit "edit comment", class: 'main__profile__history__comments__content__btnsubmit'%>
                <%# link_to 'Destroy', '/comments/' + ea_comment.id.to_s, method: :delete %>
              <% end %>

            </li>
          <% end %>
          
        </div>
        
      </ul>

    </div>



  <% end %>

  <% if @page_user.blogs.all.length == 0 %>
    <br>
    <div class="main__landing__title_highlight">
      This user has no blogs.
    </div>
  <% end %>
</div>

<!-- div for javascript to find -->

<div class="main__profile_loaded"></div>